version: '3'

services:
 bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot_qiwi
    entrypoint: python main.py
    env_file:
      - .env
    networks:
      - telegram_bot_qiwi
    logging:
      options:
        max-size: 10m

networks:
  telegram_bot_qiwi:
    driver: bridge